### ISSUE TITLE
Calculation of the reward

### ISSUE THREAD

**Issue by MNUEL174** [MarvinD00/LearningAgent#3]
The agent needs a reward to learn from its mistakes. How the reward system works is currently unknown.

**Comment by MarvinD00** [comment]
currently on this will commit end of game logic now and then work on score system

**Comment by MarvinD00** [comment]
will start this now , my idea:
for every "move down"  the player does -> 10 score (if you make the tetrimino move down faster you should be rewarded imho
                                                                                   because you make the game harder this way)
every second -> 5 score
1 tetris -> 100 score
2 tetris combo -> 250 score
3 tetris combo -> 400 score
4 tetris combo -> 600 score

**Comment by MarvinD00** [comment]
switched every second with move down
move down is 5 score
every second is 10 score
commit coming soon tm
